package model.vo;

import java.math.BigDecimal;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 07 15:26:44 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxfndAttachment_EOViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxfndAttachment_EOViewImpl() {
    }

    /**
     * Returns the variable value for b_SrcDocId.
     * @return variable value for b_SrcDocId
     */
    public BigDecimal getb_SrcDocId() {
        return (BigDecimal) ensureVariableManager().getVariableValue("b_SrcDocId");
    }

    /**
     * Sets <code>value</code> for variable b_SrcDocId.
     * @param value value to bind as b_SrcDocId
     */
    public void setb_SrcDocId(BigDecimal value) {
        ensureVariableManager().setVariableValue("b_SrcDocId", value);
    }
}

